apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-load-balancer-controller
  namespace: kube-system
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::767224848720:role/eksctl-test-cluster-addon-iamserviceaccount-k-Role1-3BuKfvYD6X2c
