#!/bin/bash

echo "=== Lambda Layer Update Pull Request ==="
echo ""
echo "Changes made:"
echo "1. Created new Lambda layer 'CommonDependenciesLayer' with dependencies:"
echo "   - requests==2.31.0"
echo "   - boto3==1.34.0" 
echo "   - pydantic==2.5.0"
echo ""
echo "2. Updated all Lambda functions to use the new layer"
echo "3. Enhanced add.py to use Pydantic for input validation"
echo ""
echo "Files changed:"
echo "- layers/common-deps/requirements.txt (new)"
echo "- template.yaml (updated)"
echo "- lambdas/add/add.py (updated)"
echo ""
echo "To create the pull request:"
echo "1. Set up GitHub authentication (personal access token)"
echo "2. Run: git push -u origin feature/update-lambda-layer-dependencies"
echo "3. Go to GitHub and create a pull request from the branch"
echo ""
echo "Pull Request Title: Update Lambda layer with new dependencies"
echo ""
echo "Pull Request Description:"
echo "This PR adds a new Lambda layer with common dependencies and updates all Lambda functions to use it."
echo ""
echo "### Changes:"
echo "- **New Lambda Layer**: Added \`CommonDependenciesLayer\` with requests, boto3, and pydantic"
echo "- **Updated Functions**: All Lambda functions now reference the new layer"
echo "- **Enhanced Validation**: Updated add.py to use Pydantic for input validation"
echo "- **Better Error Handling**: Improved error responses with proper status codes"
echo ""
echo "### Benefits:"
echo "- Centralized dependency management"
echo "- Reduced deployment package size for individual functions"
echo "- Better input validation and error handling"
echo "- Consistent dependency versions across all functions"
echo ""
echo "### Testing:"
echo "- Functions maintain backward compatibility"
echo "- Enhanced error handling for invalid inputs"
echo "- Metadata includes function version information"
