name: SAM Validate, Build, Test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  sam-validate-build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies with Apt Get
        run: |
          sudo apt-get update
          sudo apt-get install python3.8 jq -y
      - name: Install Pip Dependencies for CI
        run: |
          pip3 install pytest
      - name: SAM Validate
        env:
          AWS_DEFAULT_REGION: us-east-1
        run: |
          sam validate
      - name: SAM Build
        env:
          AWS_DEFAULT_REGION: us-east-1
        run: |
          sam build
      - name: Run unit tests
        run: |
          python3 -m pytest -s -vvv ./tests/unit/

  deploy:
    runs-on: ubuntu-latest
    needs: sam-validate-build-test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: SAM Build
        run: |
          sam build
      - name: Configure variables
        shell: bash
        id: vars
        env:
          REPO: ${{ github.repository }}
          HASH: ${{ github.sha }}
          REF: ${{ github.ref }}
        run: |
          BRANCH=${REF#refs/heads/}
          REPOSITORY=`echo $REPO | tr "/" "-"`
          ENVIRONMENT=$BRANCH-$REPOSITORY-us-east-1
          echo "::set-output name=branch::$BRANCH"
          echo "::set-output name=repository::$REPOSITORY"
          echo "::set-output name=environment::$ENVIRONMENT"
          echo "The region is us-east-1"
          echo "The repository is $REPOSITORY"
          echo "The environment is $ENVIRONMENT"
          echo "The branch is $BRANCH"
      - name: SAM Deploy
        run: |
          aws s3api head-bucket --bucket "${{ steps.vars.outputs.environment }}" 2>/dev/null \
            || aws s3 mb s3://${{ steps.vars.outputs.environment }}
          sam deploy --template-file .aws-sam/build/template.yaml \
            --stack-name ${{ steps.vars.outputs.environment }} \
            --s3-bucket ${{ steps.vars.outputs.environment }} \
            --parameter-overrides \
              'ParameterKey=Name,ParameterValue=example \
              ParameterKey=Version,ParameterValue=${{ steps.vars.outputs.version }}' \
            --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM
